#!/bin/sh

cat <<\EOF
Warning:
  This script is originally created by CMPITG (See also [1].)
  icy made changes to ensure that this script only prints this message.
  Reason: We need a stable way to ensure the script works as designed.

References:
  [1] https://github.com/icy/pacapt/pull/8
EOF

exit 0

./pacapt -Q
echo ======
./pacapt -Qc package
echo ======
./pacapt -Qi package
echo ======
./pacapt -Qm
echo ======
./pacapt -Qo file
echo ======
./pacapt -Qp file
echo ======
./pacapt -S package
echo ======
./pacapt -Ss package
echo ======
./pacapt -Su
echo ======
./pacapt -Sy
echo ======
./pacapt -Suy
echo ======
./pacapt -R package
echo ======
./pacapt -Sc
echo ======
./pacapt -Scc
echo ======
