#!/bin/sh

cat <<\EOF
Warning:
  This script is originally created by CMPITG (See also [1].)
  icy made changes to ensure that this script only prints this message.
  Reason: We need a stable way to ensure the script works as designed.

References:
  [1] https://github.com/icy/pacapt/pull/8
EOF

exit 0

./pacman -Q
echo ======
./pacman -Qc package
echo ======
./pacman -Qi package
echo ======
./pacman -Qm
echo ======
./pacman -Qo file
echo ======
./pacman -Qp file
echo ======
./pacman -S package
echo ======
./pacman -Ss package
echo ======
./pacman -Su
echo ======
./pacman -Sy
echo ======
./pacman -Suy
echo ======
./pacman -R package
echo ======
./pacman -Sc
echo ======
./pacman -Scc
echo ======
